parameters:
#    parameter_name: value

services:
#    service_name:
#        class: Store\---Bundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
