#not needed, kept as example couse include in main routiung !!!

#store_user_homepage:
#    path:     /
#    defaults: { _controller: StoreUserBundle:Default:index }

#store_users:
#    resource: "@StoreUserBundle/Controller/"
#    type:   annotation